version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - app-network
    restart: unless-stopped

  llmservice:
    image: ollama/ollama
    container_name: llmservice
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    networks:
      - app-network
    restart: unless-stopped
    command: ["ollama", "run", "deepseek-r1:1.5b"]

  backend:
    build:
      context: ./backend
    container_name: backend-fastapi
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - qdrant
      - llmservice
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  qdrant_storage:
  ollama_storage:
